name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Replace jobe
      uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEV_DEPLOY_KEY }}
        with:
          options: '--exclude=.git'
          src: '.'
          dist: '${{ secrets.DEV_USERNAME }}@${{ secrets.DEV_HOST }}:/var/www/jobe'
